nginx:
  image: spotscore/nginx-proxy
  ports:
   - "80:80"
  links:
   - spotscore
spotscore:
  image: spotscore/spotscore
  ports:
   - "3000:3000"
  links:
   - postgis
postgis:
  image: spotscore/postgis
